// ============================================================================
// tb_ps2_keyboard.v - Testbench for ps2_keyboard module
// Simulates PS/2 bus manually to send W, S, Up arrow, Down arrow, Enter
// ============================================================================
`timescale 1ns / 1ps

module tb_ps2_keyboard;

    reg        clk;
    reg        rst_n;
    wire       PS2_clk;
    wire       PS2_data;
    wire       left_up, left_down, right_up, right_down, start_pause;

    // We drive the inout bus via tri-state
    reg  ps2_clk_out;
    reg  ps2_data_out;
    reg  drive_bus;     // 1 = drive bus
    assign PS2_clk = drive_bus ? ps2_clk_out : 1'bz;
    assign PS2_data = drive_bus ? ps2_data_out : 1'bz;

    ps2_keyboard DUT (
        .clk         (clk),
        .rst_n       (rst_n),
        .PS2_clk     (PS2_clk),
        .PS2_data    (PS2_data),
        .left_up     (left_up),
        .left_down   (left_down),
        .right_up    (right_up),
        .right_down  (right_down),
        .start_pause (start_pause)
    );

    // 25.175 MHz clock
    always #19.86 clk = ~clk;

    // ------------------------------------------------------------------------
    // Task: send one PS/2 frame (11 bits: start, 8 data, parity, stop)
    // Data is sent LSB first, clock generated by host
    // ------------------------------------------------------------------------
    task send_ps2;
        input [7:0] data;
        integer i;
        reg parity;
        begin
            // Start bit (0)
            ps2_data_out = 1'b0;
            // Clock low for 30 us, then high for 30 us -> approx 16.7 kHz
            #15000; ps2_clk_out = 1'b0; #15000; ps2_clk_out = 1'b1;
            #15000; ps2_clk_out = 1'b0; #15000; ps2_clk_out = 1'b1;

            // 8 data bits, LSB first
            parity = 1'b0;
            for (i = 0; i < 8; i = i + 1) begin
                ps2_data_out = data[i];
                parity = parity ^ data[i];
                // Clock pulse
                #15000; ps2_clk_out = 1'b0; #15000; ps2_clk_out = 1'b1;
            end

            // Parity bit (odd: parity bit makes total ones odd)
            ps2_data_out = ~parity; // odd parity
            #15000; ps2_clk_out = 1'b0; #15000; ps2_clk_out = 1'b1;

            // Stop bit (1)
            ps2_data_out = 1'b1;
            #15000; ps2_clk_out = 1'b0; #15000; ps2_clk_out = 1'b1;

            // Release bus
            #15000;
        end
    endtask

    initial begin
        clk = 0;
        rst_n = 0;
        drive_bus = 1;
        ps2_clk_out = 1;
        ps2_data_out = 1;

        #200 rst_n = 1;
        #1000;

        // Send W make code: 0x1D
        send_ps2(8'h1D);
        #50000;
        // Send W break code: 0xF0, 0x1D (two frames)
        send_ps2(8'hF0);
        #200;
        send_ps2(8'h1D);
        #50000;

        // Send S make code: 0x1B
        send_ps2(8'h1B);
        #50000;
        // Break S
        send_ps2(8'hF0);
        #200;
        send_ps2(8'h1B);
        #50000;

        // Send Up arrow (E0, 0x75)
        send_ps2(8'hE0);
        #200;
        send_ps2(8'h75);
        #50000;
        // Break Up arrow (E0, 0xF0, 0x75)
        send_ps2(8'hE0);
        #200;
        send_ps2(8'hF0);
        #200;
        send_ps2(8'h75);
        #50000;

        // Send Enter make: 0x5A
        send_ps2(8'h5A);
        #50000;
        // Break Enter
        send_ps2(8'hF0);
        #200;
        send_ps2(8'h5A);
        #50000;

        #20000 $stop;
    end

endmodule